import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import { spellingMatches } from '../src/tokenizer.js';
import { alignSentenceInput } from '../src/textsentences.js';
import { addSentenceEntry, deleteSentenceEntry, deleteSentenceBook, deriveSentencePracticeStatus, deriveWholeSentenceStatus, deriveSplitSentenceStatus, recordWholeSentenceAttempt, setSplitSentencePracticeStatus } from '../src/sentencebooks.js';
import { defaultState, normalizeState } from '../src/storage.js';

test('numeric equivalence is symmetric',()=>{assert.equal(spellingMatches('twenty five','25'),true);assert.equal(spellingMatches('25','twenty five'),true);assert.equal(spellingMatches('eight thirty','8:30'),true);assert.equal(spellingMatches('sixth','6th'),true);assert.equal(spellingMatches('twenty six','25'),false);});
test('whole sentence alignment accepts spoken numeric spans',()=>{assert.equal(alignSentenceInput('The fee is £25 on the 6th.','The fee is twenty five pounds on the sixth').correct,true);assert.equal(alignSentenceInput('Meet me at 8:30.','Meet me at eight thirty').correct,true);});
test('whole and split states stay independent',()=>{const s={sentenceBooks:[],words:[],simpleWords:[]};const {entry}=addSentenceEntry(s,{bookName:'A',text:'Rural areas are quiet.',tokens:['Rural','areas','are','quiet']});recordWholeSentenceAttempt(entry,{input:'Rural areas quiet',alignment:{correct:false,distance:1,operations:[]}});setSplitSentencePracticeStatus(entry,'done');assert.equal(deriveWholeSentenceStatus(entry),'repeat');assert.equal(deriveSplitSentenceStatus(entry),'done');assert.equal(deriveSentencePracticeStatus(entry),'repeat');recordWholeSentenceAttempt(entry,{input:'Rural areas are quiet',alignment:{correct:true,distance:0,operations:[]}});assert.equal(deriveSentencePracticeStatus(entry),'done');});
test('sentence deletion does not delete vocabulary',()=>{const s={sentenceBooks:[],words:[{id:'w1',en:'rural'}],simpleWords:[]};const a=addSentenceEntry(s,{bookName:'A',text:'One.',tokens:['One']});addSentenceEntry(s,{bookName:'A',text:'Two.',tokens:['Two']});assert.equal(deleteSentenceEntry(s,a.book.id,a.entry.id).removedEntries,1);assert.equal(deleteSentenceBook(s,a.book.id).removedEntries,1);assert.equal(s.words.length,1);});
test('sentence session survives normalization',()=>{const s=defaultState();s.sentenceSession={mode:'whole',updatedAt:123,run:{bookId:'b1',entryId:'e1',input:'half written',revealed:false,peek:false},queue:[{bookId:'b1',entryId:'e2'}]};const n=normalizeState(s);assert.equal(n.sentenceSession.run.input,'half written');assert.equal(n.sentenceSession.queue.length,1);});
test('sentence UI wires recovery and daily-use controls',()=>{const app=fs.readFileSync(new URL('../src/app.js',import.meta.url),'utf8');for(const needle of ['SENTENCE_DRAFT_KEY','scheduleSentenceDraftPersist','wholeSlow','data-delete-sentence-entry','data-delete-sentence-book','startQuickSplit','startFreeListenBatch','setSplitSentencePracticeStatus'])assert.ok(app.includes(needle),needle);});
