from pathlib import Path
import re

p=Path('src/app.js')
s=p.read_text(encoding='utf-8')
if "studyDayLabel" in s and "sentenceRun" in s and "todayNewTarget" in s:
    print('v4 app changes already applied')
    raise SystemExit(0)

old_imports="""import { loadState, saveState, replaceState, exportState } from './storage.js';
import { dayKey, uid, recordAttempt, editAttempt, eventsOnDay, latestEventOnDay, rebuildAllCards } from './engine.js';
import { allBooks, matchesBooks, ensureDailyPlan, planStatus, todayListeningStats, createRetrySession, pickNext, finishCurrent, sessionProgress, dueForecast } from './queue.js';
import { retrievability, FSRS_VERSION } from './scheduler.js';
"""
new_imports=old_imports+"import { addStudyDays, calendarDate, calendarKey, studyDayLabel } from './studyday.js';\nimport { tokenizeEnglish, spellingMatches } from './tokenizer.js';\n"
if old_imports not in s: raise SystemExit('imports not found')
s=s.replace(old_imports,new_imports,1)

s=s.replace("let textFormOpen = false;\nlet statRange = 30;\nlet statDay = dayKey();\nlet statMonth = new Date(new Date().getFullYear(), new Date().getMonth(), 1);",
            "let textFormOpen = false;\nlet sentenceRun = null;\nlet statRange = 30;\nlet statDay = dayKey();\nlet statMonth = calendarDate(statDay);",1)
s=s.replace("function dateObj(key) { const [y, m, d] = key.split('-').map(Number); return new Date(y, m - 1, d); }","function dateObj(key) { return calendarDate(key); }",1)
s=s.replace("function go(next) { speechSynthesis?.cancel(); view = next; listen = null; typeRun = null; textReaderId = null; render(); }","function go(next) { speechSynthesis?.cancel(); view = next; listen = null; typeRun = null; sentenceRun = null; textReaderId = null; render(); }",1)
s=s.replace("function eventsSince(days) { const d = new Date(); d.setDate(d.getDate() - days + 1); const key = dayKey(d.getTime()); return state.events.filter(e => e.date >= key); }","function eventsSince(days) { const key = addStudyDays(dayKey(), -days + 1); return state.events.filter(e => e.date >= key); }",1)
s=s.replace("function filteredEvents(){if(!statRange)return state.events;const d=new Date();d.setDate(d.getDate()-statRange+1);const key=dayKey(d.getTime());return state.events.filter(e=>e.date>=key);}","function filteredEvents(){if(!statRange)return state.events;const key=addStudyDays(dayKey(),-statRange+1);return state.events.filter(e=>e.date>=key);}",1)

new_today=r'''function renderToday() {
  const books = state.settings.todayBooks || [];
  const plan = ensureDailyPlan(state, { books }); persist();
  const prog = sessionProgress(state, plan, null); const td = todayListeningStats(state, books); const mins = activityMinutes('listen');
  const selectedText = books.length ? books.join('、') : '全部词书';
  const bookRows = (books.length ? books : allBooks(state)).map((b) => { const x = todayListeningStats(state, [b]); return `<div class="bookrow"><b>${esc(b)}</b><span>${x.newCount} 新</span><span>${x.reviewCount} 复习</span><span class="mobilehide good">${x.firstGood} 熟悉</span><span class="mobilehide bad">${x.firstBad} 不熟</span></div>`; }).join('');
  shell(`<div class="stack"><section class="card hero"><div class="space"><div><h2>今天先完成这一组</h2><div class="small">${esc(selectedText)} · ${studyDayLabel()}</div></div><span class="tag">FSRS</span></div><div class="plan" style="margin-top:15px"><div class="statbox"><b>${prog.newDone} / ${prog.newTotal}</b><span>新词</span><div class="progressline"><i style="width:${prog.newTotal ? prog.newDone * 100 / prog.newTotal : 0}%"></i></div></div><div class="statbox"><b>${prog.reviewDone} / ${prog.reviewTotal}</b><span>复习</span><div class="progressline"><i style="width:${prog.reviewTotal ? prog.reviewDone * 100 / prog.reviewTotal : 0}%"></i></div></div><div class="statbox"><b class="${prog.retry ? 'bad' : ''}">${prog.retry}</b><span>待巩固</span><div class="small">不增加新词/复习分母</div></div></div><div class="row" style="margin-top:16px"><button id="startListen" class="primary">${prog.remaining ? '继续今日听音' : '今日已完成'}</button><span class="small">听音 ${mins} 分钟 · 首轮熟悉 ${pct(td.firstGood, td.firstGood + td.firstBad)}</span></div><details class="details"><summary>调整今天的计划与词书</summary><div style="margin-top:12px"><div class="small">这里只改今天。降低目标时只裁掉完全没碰过的词；已经听过的词不会被删除，也不会出现 36 / 30。</div>${bookChips(books, 'today')}<div class="grid2" style="margin-top:12px"><div class="field"><label>今天新词目标</label><input id="todayNewTarget" type="number" min="0" value="${plan.newTarget}"></div><div class="field"><label>今天复习目标</label><input id="todayReviewTarget" type="number" min="0" value="${plan.reviewTarget}"></div></div></div></details><details class="details"><summary>以后每天的默认目标</summary><div class="grid2" style="margin-top:12px"><div class="field"><label>以后默认新词</label><input id="defaultNewTarget" type="number" min="0" value="${state.settings.defaultNewTarget}"></div><div class="field"><label>以后默认复习</label><input id="defaultReviewTarget" type="number" min="0" value="${state.settings.defaultReviewTarget}"></div></div><div class="small" style="margin-top:8px">修改这里不会改变今天已经生成的计划，从下一个学习日开始使用。</div></details></section><section class="card"><h2 class="section-title">今日听音数据</h2><div class="grid4" style="margin-top:13px"><div class="statbox"><b>${td.newCount}</b><span>听音新词</span></div><div class="statbox"><b>${td.reviewCount}</b><span>听音复习</span></div><div class="statbox"><b class="good">${td.firstGood}</b><span>首轮熟悉</span></div><div class="statbox"><b class="bad">${td.firstBad}</b><span>首轮不熟</span></div></div></section><section class="card"><h2 class="section-title">各词书今天的情况</h2><div class="small">只统计听音，不混入手打。</div><div style="margin-top:8px">${bookRows || '<div class="empty">还没有词书。</div>'}</div></section></div>`);
  bindBookChips('today', renderToday);
  document.getElementById('todayNewTarget').onchange = (e) => { const requested=Math.max(0,Number(e.target.value)||0); const updated=ensureDailyPlan(state,{newTarget:requested}); persist(); if(updated.newTarget!==requested)toast(`今天已经做过 ${updated.newTarget} 个新词，目标不能再降`); renderToday(); };
  document.getElementById('todayReviewTarget').onchange = (e) => { const requested=Math.max(0,Number(e.target.value)||0); const updated=ensureDailyPlan(state,{reviewTarget:requested}); persist(); if(updated.reviewTarget!==requested)toast(`今天已经做过 ${updated.reviewTarget} 个复习词，目标不能再降`); renderToday(); };
  document.getElementById('defaultNewTarget').onchange = (e) => { state.settings.defaultNewTarget=Math.max(0,Number(e.target.value)||0); persist(); toast('已修改以后每天的新词默认值'); };
  document.getElementById('defaultReviewTarget').onchange = (e) => { state.settings.defaultReviewTarget=Math.max(0,Number(e.target.value)||0); persist(); toast('已修改以后每天的复习默认值'); };
  document.getElementById('startListen').onclick = () => { if (!prog.remaining) return toast('今天这一组已经完成'); startListen(plan); };
}

function startListen'''
s,n=re.subn(r'function renderToday\(\) \{.*?\n\}\n\nfunction startListen',new_today,s,count=1,flags=re.S)
if n!=1: raise SystemExit(f'renderToday replace failed {n}')

new_text=r'''function renderText(){
  if(textReaderId)return renderTextReader();
  const cols=[...new Set(state.texts.map(t=>t.collection||'未分类'))].sort(); const editing=textEditId?state.texts.find(t=>t.id===textEditId):null;
  shell(`<div class="stack"><section class="card hero"><div class="space"><div><h2>文本库</h2><p>保存 transcript 和文章，之后直接继续听，不用重新粘贴。</p></div><button id="newText" class="primary">${textFormOpen||editing?'收起':'新建文本'}</button></div><div class="grid3" style="margin-top:13px"><div class="statbox"><b>${state.texts.length}</b><span>篇文本</span></div><div class="statbox"><b>${cols.length}</b><span>个文本库</span></div><div class="statbox"><b>${state.texts.reduce((n,t)=>n+(t.body.match(/[A-Za-z]+/g)?.length||0),0)}</b><span>英文词量</span></div></div></section><section class="card"><h2 class="section-title">句子拆词听写</h2><div class="small">粘一句英文，自动按实际词形拆开。这里是拼写听写，不改 FSRS 熟练度。</div><textarea id="sentenceDictationText" style="min-height:105px;margin-top:10px" placeholder="The farmers are working in rural areas."></textarea><div class="row" style="margin-top:10px"><label class="small"><input id="sentenceUnique" type="checkbox" style="width:auto"> 去重后听写</label><button id="startSentenceDictation" class="primary">开始拆词听写</button></div><div id="sentencePreview" class="source-tags" style="justify-content:flex-start;margin-top:10px"></div></section>${textFormOpen||editing?`<section class="card"><h2 class="section-title">${editing?'编辑文本':'新建文本'}</h2><div class="grid2" style="margin-top:12px"><div class="field"><label>标题</label><input id="textTitle" value="${esc(editing?.title||'')}" placeholder="Test 3 Part 4"></div><div class="field"><label>所属文本库</label><input id="textCollection" value="${esc(editing?.collection||'')}" placeholder="剑18"></div></div><textarea id="textBody" style="margin-top:10px" placeholder="粘贴 transcript / 文章正文…">${esc(editing?.body||'')}</textarea><div class="row" style="margin-top:10px"><button id="saveText" class="primary">保存</button><button id="importTextFile" class="soft">导入 TXT</button></div></section>`:''}<section class="card"><div class="space"><div><h2 class="section-title">我的文本</h2><div class="small">按库筛选或搜索标题/正文。</div></div></div><div class="grid2" style="margin-top:12px"><input id="textSearch" placeholder="搜索文本"><select id="textFilter"><option value="">全部文本库</option>${cols.map(c=>`<option>${esc(c)}</option>`).join('')}</select></div><div id="textList" class="list" style="margin-top:12px"></div></section></div>`);
  document.getElementById('newText').onclick=()=>{textFormOpen=!textFormOpen;if(!textFormOpen)textEditId=null;renderText();};
  if(textFormOpen||editing){document.getElementById('saveText').onclick=saveTextItem;document.getElementById('importTextFile').onclick=()=>textInput.click();}
  const sentenceBox=document.getElementById('sentenceDictationText'),unique=document.getElementById('sentenceUnique'),preview=document.getElementById('sentencePreview');
  const drawSentencePreview=()=>{const tokens=tokenizeEnglish(sentenceBox.value,{unique:unique.checked});preview.innerHTML=tokens.slice(0,30).map(x=>`<span class="tag">${esc(x)}</span>`).join('')+(tokens.length>30?`<span class="tag">… 共 ${tokens.length} 个</span>`:'');};
  sentenceBox.oninput=drawSentencePreview; unique.onchange=drawSentencePreview; document.getElementById('startSentenceDictation').onclick=()=>startSentenceDictation(sentenceBox.value,unique.checked);
  document.getElementById('textSearch').oninput=drawTextList;document.getElementById('textFilter').onchange=drawTextList;drawTextList();
}
function startSentenceDictation(text,unique){const tokens=tokenizeEnglish(text,{unique});if(!tokens.length)return toast('这句话里没有识别到英文单词');sentenceRun={tokens,index:0,input:'',result:null,revealed:false,lookups:0,correct:0};renderSentenceRun();speak(tokens[0]);}
function renderSentenceRun(){const token=sentenceRun.tokens[sentenceRun.index];if(!token)return finishSentenceRun();root.innerHTML=`<main class="immersive"><div class="studytop"><button id="sentenceBack" class="back">‹</button><div class="studyprogress">${sentenceRun.index+1} / ${sentenceRun.tokens.length} · 句子拆词听写</div></div><div class="studybody"><button id="sentenceSpeak" class="speaker">◖))</button>${!sentenceRun.revealed?`<div class="small">听单词，写出英文拼写。</div><div style="width:100%;max-width:560px;margin-top:18px"><input id="sentenceAnswer" style="font-size:21px;text-align:center" placeholder="输入英文拼写…" autocomplete="off" autocapitalize="off"><div class="grid2" style="margin-top:10px"><button id="sentenceSubmit" class="primary">提交</button><button id="sentenceReveal" class="soft">看答案</button></div></div>`:`<div class="word ${sentenceRun.result==='good'?'good':'bad'}">${esc(token)}</div><div class="typed"><b>你写的是</b><div>${esc(sentenceRun.input||'（直接看答案）')}</div></div><div class="statusline">${sentenceRun.result==='good'?'拼写正确':'已显示正确拼写'}</div><div class="move"><button id="sentenceReplay" class="soft">重听</button><button id="sentenceNext" class="primary">下一词</button></div>`}</div></main>`;document.getElementById('sentenceBack').onclick=()=>{sentenceRun=null;view='text';renderText();};document.getElementById('sentenceSpeak').onclick=()=>speak(token);if(!sentenceRun.revealed){const input=document.getElementById('sentenceAnswer');input.value=sentenceRun.input;input.focus();const reveal=(peek)=>{sentenceRun.input=input.value.trim();sentenceRun.result=!peek&&spellingMatches(sentenceRun.input,token)?'good':'bad';if(sentenceRun.result==='good')sentenceRun.correct++;else sentenceRun.lookups++;sentenceRun.revealed=true;renderSentenceRun();};document.getElementById('sentenceSubmit').onclick=()=>{if(!input.value.trim())return toast('没写的话可以点「看答案」');reveal(false);};document.getElementById('sentenceReveal').onclick=()=>reveal(true);input.onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();input.value.trim()?reveal(false):reveal(true);}};}else{document.getElementById('sentenceReplay').onclick=()=>speak(token);document.getElementById('sentenceNext').onclick=()=>{sentenceRun.index++;sentenceRun.input='';sentenceRun.result=null;sentenceRun.revealed=false;if(sentenceRun.index>=sentenceRun.tokens.length)finishSentenceRun();else{renderSentenceRun();speak(sentenceRun.tokens[sentenceRun.index]);}};}}
function finishSentenceRun(){const run=sentenceRun;root.innerHTML=`<main class="immersive"><div class="studybody"><div class="finish"><div class="small">本轮完成</div><h2>句子拆词听写</h2><div class="grid3" style="margin:18px 0"><div class="statbox"><b>${run.tokens.length}</b><span>单词数</span></div><div class="statbox"><b class="good">${run.correct}</b><span>一次拼对</span></div><div class="statbox"><b class="bad">${run.lookups}</b><span>错误/看答案</span></div></div><button id="finishSentence" class="primary">返回文本</button></div></div></main>`;document.getElementById('finishSentence').onclick=()=>{sentenceRun=null;view='text';renderText();};}
function drawTextList()'''
s,n=re.subn(r'function renderText\(\)\{.*?\}\nfunction drawTextList\(\)',new_text,s,count=1,flags=re.S)
if n!=1: raise SystemExit(f'renderText replace failed {n}')

new_calendar=r'''function calendarHtml(){const activity={};state.events.forEach(e=>activity[e.date]=(activity[e.date]||0)+1);const first=new Date(Date.UTC(statMonth.getUTCFullYear(),statMonth.getUTCMonth(),1,12)),last=new Date(Date.UTC(statMonth.getUTCFullYear(),statMonth.getUTCMonth()+1,0,12)),offset=(first.getUTCDay()+6)%7,start=new Date(first);start.setUTCDate(first.getUTCDate()-offset);const tail=6-((last.getUTCDay()+6)%7),end=new Date(last);end.setUTCDate(last.getUTCDate()+tail);const cells=[];let max=1;for(let d=new Date(start);d<=end;d.setUTCDate(d.getUTCDate()+1)){const key=calendarKey(d),n=activity[key]||0;max=Math.max(max,n);cells.push({key,n,date:new Date(d),same:d.getUTCMonth()===first.getUTCMonth()});}return`<section class="card"><div class="space"><div><h2 class="section-title">学习日历</h2><div class="small">${studyDayLabel()}。可以一直往前翻，点日期看具体记录。</div></div></div><div class="calendarbar"><button id="calPrev">‹</button><div><b>${first.getUTCFullYear()} 年 ${first.getUTCMonth()+1} 月</b></div><button id="calNext">›</button></div><div class="week"><span>一</span><span>二</span><span>三</span><span>四</span><span>五</span><span>六</span><span>日</span></div><div class="calgrid">${cells.map(c=>{const future=c.key>dayKey(),op=c.n?.14+.62*c.n/max:.04;return`<button class="day ${c.key===statDay?'sel ':''}${c.same?'':'other '}${future?'future':''}" data-stat-day="${c.key}" ${future?'disabled':''} style="background:rgba(93,119,99,${op.toFixed(2)})"><span>${c.date.getUTCDate()}</span>${c.n?`<strong>${c.n}</strong>`:''}</button>`;}).join('')}</div><div style="text-align:center;margin-top:8px"><button id="calToday" class="ghost">回到本月</button></div></section>`;}
function bindCalendar(){document.getElementById('calPrev').onclick=()=>{statMonth=new Date(Date.UTC(statMonth.getUTCFullYear(),statMonth.getUTCMonth()-1,1,12));renderStats();};document.getElementById('calNext').onclick=()=>{const n=new Date(Date.UTC(statMonth.getUTCFullYear(),statMonth.getUTCMonth()+1,1,12)),cur=calendarDate(dayKey());cur.setUTCDate(1);if(n<=cur){statMonth=n;renderStats();}};document.getElementById('calToday').onclick=()=>{statDay=dayKey();statMonth=calendarDate(statDay);renderStats();};document.querySelectorAll('[data-stat-day]').forEach(b=>b.onclick=()=>{statDay=b.dataset.statDay;statMonth=calendarDate(statDay);renderStats();});}
function dayDetailHtml'''
s,n=re.subn(r'function calendarHtml\(\)\{.*?\}\nfunction bindCalendar\(\)\{.*?\}\nfunction dayDetailHtml',new_calendar,s,count=1,flags=re.S)
if n!=1: raise SystemExit(f'calendar replace failed {n}')

old_render="function render(){try{if(listen)return renderListen();if(typeRun)return renderTypeRun();if(textReaderId)return renderTextReader();if(view==='home')renderHome();else if(view==='today')renderToday();else if(view==='type')renderType();else if(view==='text')renderText();else if(view==='library')renderLibrary();else renderStats();}catch(err){console.error(err);root.innerHTML=`<div class=\"app-error card\"><h2>页面渲染失败</h2><p>数据没有被清空。刷新后仍有问题可以把这段发给我。</p><pre>${esc(err?.stack||err)}</pre></div>`;}}"
new_render="function render(){try{if(listen)return renderListen();if(typeRun)return renderTypeRun();if(sentenceRun)return renderSentenceRun();if(textReaderId)return renderTextReader();if(view==='home')renderHome();else if(view==='today')renderToday();else if(view==='type')renderType();else if(view==='text')renderText();else if(view==='library')renderLibrary();else renderStats();}catch(err){console.error(err);root.innerHTML=`<div class=\"app-error card\"><h2>页面渲染失败</h2><p>数据没有被清空。刷新后仍有问题可以把这段发给我。</p><pre>${esc(err?.stack||err)}</pre></div>`;}}"
if old_render not in s: raise SystemExit('render dispatcher not found')
s=s.replace(old_render,new_render,1)

p.write_text(s,encoding='utf-8')
print('applied v4 app changes')
