from pathlib import Path
import re

p = Path('index.html')
s = p.read_text(encoding='utf-8')

if 'data-hand-v2' in s:
    print('hand mode v2 already present')
    raise SystemExit(0)

css = r'''
/* data-hand-v2 */
.handHero{padding:22px}.handHero h2{font-size:25px;margin:0 0 6px}.handHero p{margin:0;color:var(--muted);line-height:1.6}.quickGrid{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:14px}.quickCard{border:1px solid var(--line);background:#fffdfa;border-radius:18px;padding:16px;text-align:left;min-height:96px}.quickCard b{display:block;font-size:17px;margin-bottom:5px}.quickCard .qnum{font-size:26px;font-weight:730;float:right;margin-left:8px}.quickCard .small{font-size:12px}.handFilter{margin-top:14px}.filterGrid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.filterGrid .field{min-width:0}.filterGrid input,.filterGrid select{width:100%}.matchBox{display:flex;justify-content:space-between;align-items:center;gap:14px;margin-top:16px;padding-top:14px;border-top:1px solid rgba(80,75,65,.1)}.matchNum{font-size:24px;font-weight:730}.previewWords{display:flex;gap:6px;flex-wrap:wrap;margin-top:10px}.previewWord{font-size:12px;border:1px solid var(--line);background:#fffdfa;border-radius:999px;padding:5px 8px;color:#64665f}.focusType .top,.focusType .nav{display:none!important}.focusType .wrap{max-width:none;padding:0!important}.focusType #type{display:block;min-height:100dvh}.typeStudy{min-height:100dvh;border:0!important;border-radius:0!important;box-shadow:none!important;background:var(--bg)!important;padding:112px 22px 118px!important}.typeTop{position:absolute;top:0;left:0;right:0;height:90px;padding:max(16px,env(safe-area-inset-top)) 20px 0;display:flex;align-items:center;justify-content:center;z-index:3}.typeBack{position:absolute;left:16px;top:max(14px,env(safe-area-inset-top));width:48px;height:48px;border:0;background:transparent;border-radius:50%;font-size:40px;font-weight:300;line-height:40px;padding:0}.typeProgress{font-size:14px;color:var(--muted)}.typeInputWrap{width:100%;max-width:560px}.typeInput{width:100%;font-size:22px;text-align:center;padding:16px 14px;margin-top:18px}.typeActions{display:grid;grid-template-columns:1fr 1fr;gap:10px;width:100%;max-width:560px;margin-top:12px}.typeActions button{padding:14px 10px}.answerMeta{display:flex;justify-content:center;gap:6px;flex-wrap:wrap;margin-top:12px}.answerTag{font-size:12px;border:1px solid var(--line);background:#fffdfa;border-radius:999px;padding:4px 8px;color:var(--muted)}.typedAnswer{width:100%;max-width:560px;margin-top:18px;padding:12px 14px;border-radius:14px;background:rgba(255,255,255,.48);text-align:left}.typedAnswer b{font-size:12px;color:var(--muted);font-weight:600}.typedAnswer div{margin-top:4px;font-size:16px}.typeFinish{text-align:center;padding:30px}.finishStats{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin:18px 0}.finishBox{background:#fffdfa;border:1px solid var(--line);border-radius:16px;padding:14px 8px}.finishBox b{display:block;font-size:25px}.finishBox span{font-size:12px;color:var(--muted)}
@media(max-width:560px){.quickGrid{grid-template-columns:1fr 1fr}.quickCard{padding:14px;min-height:92px}.filterGrid{grid-template-columns:1fr}.typeStudy{padding-left:18px!important;padding-right:18px!important}.finishStats{grid-template-columns:repeat(3,1fr)}}
'''
if '</style>' not in s:
    raise SystemExit('style tag not found')
s = s.replace('</style>', css + '</style>', 1)

s = s.replace("document.body.classList.remove('focusStudy');", "document.body.classList.remove('focusStudy','focusType');", 1)

new_block = r'''function typeBooks(){var a=[];S.words.forEach(function(w){(w.src||[]).forEach(function(x){if(a.indexOf(x)<0)a.push(x)})});return a.sort()}
function typeDayOffset(n){var d=new Date();d.setDate(d.getDate()+n);return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0')}
function typeBadEvents(w,opt){return S.events.filter(function(e){if(e.wordId!==w.id||e.res!=='bad')return false;if(opt.date&&e.date!==opt.date)return false;if(opt.from&&e.date<opt.from)return false;if(opt.mode&&opt.mode!=='all'&&e.mode!==opt.mode)return false;return true})}
function typeQueue(opt){opt=opt||{};var words=S.words.filter(function(w){return!w.ret&&(!opt.book||(w.src||[]).indexOf(opt.book)>=0)}),scored=[];words.forEach(function(w){var bad=typeBadEvents(w,opt),allBad=S.events.filter(function(e){return e.wordId===w.id&&e.res==='bad'}),coldBad=allBad.filter(function(e){return e.cold}).length,recent=allBad.filter(function(e){return e.date>=typeDayOffset(-6)}).length;if(opt.kind==='auto'){if(!allBad.length)return;var last=allBad.length?allBad[allBad.length-1].ts:0;scored.push({w:w,score:coldBad*5+allBad.length+recent*1.5+(w.diff||0)*2+last/1e15})}else if(opt.kind==='repeat7'){var ds=new Set(bad.map(function(e){return e.date}));if(bad.length>=2||ds.size>=2)scored.push({w:w,score:ds.size*5+bad.length+(w.diff||0)})}else{if(bad.length>=(opt.min||1))scored.push({w:w,score:bad.length+(w.diff||0)})}});scored.sort(function(a,b){return b.score-a.score||a.w.en.localeCompare(b.w.en)});var q=scored.map(function(x){return x.w});if(opt.limit&&opt.limit>0)q=q.slice(0,opt.limit);return q}
function typePresetCount(kind){if(kind==='auto')return typeQueue({kind:'auto',limit:0}).length;if(kind==='todayListen')return typeQueue({kind:'filter',date:day(),mode:'listen',min:1,limit:0}).length;if(kind==='todayType')return typeQueue({kind:'filter',date:day(),mode:'type',min:1,limit:0}).length;if(kind==='repeat7')return typeQueue({kind:'repeat7',from:typeDayOffset(-6),mode:'all',limit:0}).length;return 0}
function startTypeQueue(q,label){if(!q.length){toast('这组暂时没有待强化词');return}document.body.classList.add('focusType');ts={active:true,q:q,i:0,show:false,res:null,input:'',label:label||'手打强化',done:[],skipped:0};typeCard();setTimeout(function(){if(q[0])speak(q[0].en)},60)}
function typeLanding(){if(ts&&ts.active)return typeCard();document.body.classList.remove('focusType');var books=typeBooks(),cAuto=typePresetCount('auto'),cListen=typePresetCount('todayListen'),cType=typePresetCount('todayType'),cRepeat=typePresetCount('repeat7');$('type').innerHTML='<div class="card handHero"><h2>手打强化</h2><p>优先练真正卡住过的词。默认用历史不熟记录推荐，也可以按日期、来源和词库精确筛。</p><div class="quickGrid"><button class="quickCard" data-quick="auto"><span class="qnum">'+cAuto+'</span><b>自动推荐</b><div class="small">跨天不熟权重最高，兼顾近期反复卡住</div></button><button class="quickCard" data-quick="todayListen"><span class="qnum">'+cListen+'</span><b>今日听音不熟</b><div class="small">只拿今天听音时标过不熟的词</div></button><button class="quickCard" data-quick="todayType"><span class="qnum">'+cType+'</span><b>今日手打不熟</b><div class="small">今天手打后仍然不稳的词</div></button><button class="quickCard" data-quick="repeat7"><span class="qnum">'+cRepeat+'</span><b>近 7 天反复不熟</b><div class="small">优先处理近期重复失败的词</div></button></div></div><div class="card handFilter"><div class="heatTitle"><div><b>自定义一组</b><div class="small">按你想要的范围手动筛</div></div></div><div class="filterGrid" style="margin-top:14px"><div class="field"><label>日期</label><input id="td" type="date" value="'+day()+'"></div><div class="field"><label>不熟来自哪里</label><select id="tmode"><option value="all">听音 + 手打</option><option value="listen">只看听音</option><option value="type">只看手打</option></select></div><div class="field"><label>至少标记不熟</label><select id="tm"><option value="1">1 次</option><option value="2">2 次</option><option value="3">3 次</option><option value="5">5 次</option></select></div><div class="field"><label>词库</label><select id="tbook"><option value="">全部词库</option>'+books.map(function(b){return'<option value="'+esc(b)+'">'+esc(b)+'</option>'}).join('')+'</select></div><div class="field"><label>本轮数量</label><select id="tlimit"><option value="20">20 个</option><option value="50" selected>50 个</option><option value="100">100 个</option><option value="0">全部</option></select></div></div><div id="tpreview"></div></div>';
function quick(kind){var q,label;if(kind==='auto'){q=typeQueue({kind:'auto',limit:30});label='自动推荐'}else if(kind==='todayListen'){q=typeQueue({kind:'filter',date:day(),mode:'listen',min:1,limit:50});label='今日听音不熟'}else if(kind==='todayType'){q=typeQueue({kind:'filter',date:day(),mode:'type',min:1,limit:50});label='今日手打不熟'}else{q=typeQueue({kind:'repeat7',from:typeDayOffset(-6),mode:'all',limit:50});label='近 7 天反复不熟'}startTypeQueue(q,label)}document.querySelectorAll('[data-quick]').forEach(function(b){b.onclick=function(){quick(this.dataset.quick)}});function preview(){var opt={kind:'filter',date:$('td').value,mode:$('tmode').value,min:+$('tm').value||1,book:$('tbook').value,limit:+$('tlimit').value||0},q=typeQueue(opt),all=typeQueue(Object.assign({},opt,{limit:0}));$('tpreview').innerHTML='<div class="matchBox"><div><div class="small">匹配到</div><div class="matchNum">'+all.length+' 个词</div></div><button id="tb" class="primary" '+(!q.length?'disabled':'')+'>开始这组'+(q.length?' · '+q.length:'')+'</button></div>'+(q.length?'<div class="previewWords">'+q.slice(0,10).map(function(w){return'<span class="previewWord">'+esc(w.en)+'</span>'}).join('')+(q.length>10?'<span class="previewWord">…</span>':'')+'</div>':'<div class="small" style="margin-top:10px">这个筛选条件下暂时没有不熟词。</div>');if($('tb'))$('tb').onclick=function(){startTypeQueue(q,'自定义强化')}}['td','tmode','tm','tbook','tlimit'].forEach(function(id){$(id).onchange=preview});preview()}
function typeFinish(){document.body.classList.remove('focusType');var a=ts.done||[],good=a.filter(function(x){return x.res==='good'}).length,bad=a.filter(function(x){return x.res==='bad'}).length,uniq=new Set(a.map(function(x){return x.wordId})).size,missIds=[...new Set(a.filter(function(x){return x.res==='bad'}).map(function(x){return x.wordId}))],miss=S.words.filter(function(w){return missIds.indexOf(w.id)>=0&&!w.ret});ts.active=false;$('type').innerHTML='<div class="card typeFinish"><div class="small">本轮完成</div><h2 style="font-size:28px;margin:7px 0">'+esc(ts.label||'手打强化')+'</h2><div class="finishStats"><div class="finishBox"><b>'+uniq+'</b><span>练过的词</span></div><div class="finishBox"><b class="ok">'+good+'</b><span>熟悉判断</span></div><div class="finishBox"><b class="miss">'+bad+'</b><span>不熟判断</span></div></div><div class="small">跳过手打直接看答案 '+(ts.skipped||0)+' 次</div><div class="row" style="justify-content:center;margin-top:20px">'+(miss.length?'<button id="redoBad" class="primary">再练本轮不熟 · '+miss.length+'</button>':'')+'<button id="chooseAgain" class="soft">重新选一组</button></div></div>';if($('redoBad'))$('redoBad').onclick=function(){startTypeQueue(miss,'本轮不熟再练')};$('chooseAgain').onclick=function(){ts=null;typeLanding()}}
function typeCard(){var w=ts.q[ts.i];if(!w){typeFinish();return}var top='<div class="typeTop"><button id="typeBack" class="typeBack" aria-label="返回">‹</button><div class="typeProgress">'+(ts.i+1)+' / '+ts.q.length+' · '+esc(ts.label||'手打强化')+'</div></div>';if(!ts.show){$('type').innerHTML='<div class="card study typeStudy">'+top+'<button id="tsp" class="speaker">◖))</button><div class="small">听音后写出你脑子里直接出来的中文核心意思。</div><div class="typeInputWrap"><input id="ti" class="typeInput" placeholder="写中文核心意思…" autocomplete="off"></div><div class="typeActions"><button id="tsubmit" class="primary">提交</button><button id="treveal" class="soft">看答案</button></div><div class="hint">电脑：有内容 Enter 提交；空 Enter 看答案</div></div>';$('typeBack').onclick=function(){document.body.classList.remove('focusType');ts.active=false;typeLanding()};$('tsp').onclick=function(){speak(w.en)};function reveal(skip){ts.input=$('ti').value.trim();if(skip||!ts.input)ts.skipped=(ts.skipped||0)+1;ts.show=true;typeCard()}$('tsubmit').onclick=function(){if(!$('ti').value.trim()){toast('没写内容的话直接点「看答案」');return}reveal(false)};$('treveal').onclick=function(){reveal(true)};$('ti').focus();$('ti').onkeydown=function(e){if(e.key==='Enter'){e.preventDefault();reveal(!$('ti').value.trim())}}}else{var tags=(w.src||[]).map(function(x){return'<span class="answerTag">'+esc(x)+'</span>'}).join('');$('type').innerHTML='<div class="card study typeStudy">'+top+'<button id="tsp" class="speaker">◖))</button><div class="word '+(ts.res==='good'?'good':ts.res==='bad'?'bad':'')+'">'+esc(w.en)+'</div><div class="mean">'+esc(w.zh||'暂无中文释义')+'</div>'+(w.pos||w.def?'<div class="meta">'+esc(w.pos||'')+(w.def?' · '+esc(w.def):'')+'</div>':'')+(w.ex&&w.ex.length?'<div class="ex">'+esc(w.ex[w.ex.length-1])+'</div>':'')+(tags?'<div class="answerMeta">'+tags+'</div>':'')+'<div class="typedAnswer"><b>你刚才写的是</b><div>'+esc(ts.input||'（直接看了答案）')+'</div></div><div class="judge"><button id="tg" class="goodb">1　熟悉</button><button id="tb2" class="badb">2　不熟悉</button></div><div class="hint">这里仍然只判断“熟悉 / 不熟悉”，不自动判中文同义词对错。</div><div class="mobileMove"><button id="tprev" class="soft" '+(ts.i===0?'disabled':'')+'>上一词</button><button id="tnext" class="primary" '+(!ts.res?'disabled':'')+'>下一词</button></div></div>';$('typeBack').onclick=function(){document.body.classList.remove('focusType');ts.active=false;typeLanding()};$('tsp').onclick=function(){speak(w.en)};$('tg').onclick=function(){typeJudge('good')};$('tb2').onclick=function(){typeJudge('bad')};if($('tprev'))$('tprev').onclick=typePrev;if($('tnext'))$('tnext').onclick=typeNext}}
function typeJudge(r){var w=ts.q[ts.i];if(ts.res===r)return;if(!ts.res){ev(w,'type',r);ts.done.push({wordId:w.id,res:r,ts:Date.now()})}else{var last=[...S.events].reverse().find(function(e){return e.wordId===w.id&&e.date===day()&&e.mode==='type'});if(last)last.res=r;var h=[...ts.done].reverse().find(function(e){return e.wordId===w.id});if(h)h.res=r;save()}ts.res=r;typeCard()}
function typeNext(){if(!ts||!ts.show||!ts.res)return;var w=ts.q[ts.i];if(ts.res==='bad')ts.q.push(w);ts.i++;ts.show=false;ts.res=null;ts.input='';typeCard();var n=ts.q[ts.i];if(n)setTimeout(function(){speak(n.en)},60)}
function typePrev(){if(!ts||ts.i<=0)return;ts.i--;var w=ts.q[ts.i],a=S.events.filter(function(e){return e.wordId===w.id&&e.date===day()&&e.mode==='type'}),last=a.length?a[a.length-1]:null;ts.show=true;ts.res=last?last.res:null;ts.input='';typeCard()}
function textView()'''

pattern = r'function typeLanding\(\)\{.*?function textView\(\)'
s2, n = re.subn(pattern, new_block, s, count=1, flags=re.S)
if n != 1:
    raise SystemExit(f'could not replace hand mode block: {n}')

p.write_text(s2, encoding='utf-8')
print('patched hand mode v2')
